/// Flutter icons MyCustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;


  static const IconData chevron_down = IconData(0xf078, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  //static const IconData customDropDown2 = IconData(,fontFamily: );
  static const IconData customDropDown = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customMobile = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customPassword = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customReferralCode = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
